### ISSUE TITLE
update AuthController file

### ISSUE THREAD

**Issue by madfortech** [sagautam5/changepassword#1]
update AuthController.php file 
use App\Models\User;

**Comment by sagautam5** [comment]
@madfortech Thank you so much for raising issue on this package. I have fixed this issue on this [#2 ] and tested with Laravel 9.0 version.

**Comment by sagautam5** [comment]
> update AuthController.php file use App\Models\User;

Please try this version
https://github.com/sagautam5/changepassword/releases/tag/v1.0.3
